openapi: 3.0.4
info:
  title: BajajAuto - One and Done, External Application
  description: An RestFull API service for handling request from BajajAuto internal applications.
  version: 1.0.0
  contact:
    name: BajajAuto
    email: support@bajajauto.com
    url: https://www.bajajauto.com  
servers:
  - url: https://localhost/api
  - url: https://dms.bajajauto.com/api
  - url: https://dev-dms.bajajauto.com/api
paths:
  /link:
    post:
      tags:
        - Link Generation
      summary: Generate a new document upload link for customers
      description: Generate a link for customers to upload documents, which would then be sent to the customer.
      operationId: generateLink
      requestBody:
        description: Link generation request payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/linkRequest'
        required: true
      responses:
        '201':
          description: The created response with the link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/linkResponse'
        '400':
          description: Bad Request with validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /document/search:
    get:
      tags:
        - Document Search and Download
      summary: Search for documents uploaded by a customer
      description: Get document details for given customer
      operationId: searchDocument
      parameters:
        - name: mobileNumber
          in: query
          description: Customer mobile number
          required: true
          schema:
            type: string
        - name: dealerCode
          in: query
          description: Dealer code or Identifier
          schema:
            type: string
          required: true
      responses:
        '200':
          description: The created response with the link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/documentSearchResponse'
        '400':
          description: Bad Request with validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /document/download/{documentId}:
    get:
      tags:
        - Document Search and Download
      summary: Download a specific document
      description: Download a document by its ID
      operationId: downloadDocument
      parameters:
        - name: documentId
          in: query
          description: Unique identifier of the document
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Document file download
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request with validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  schemas:
    linkRequest:
      type: object
      properties:
        mobileNumber:
          type: string
          description: The mobile number of the user
          example: "+91 9812345670"
          nullable: false
        dealerCode:
          type: string
          description: Dealer Code or Identifier.
          example: "dealer-1234"
          nullable: false
        metadata:
          type: object
          properties:
            additionalProperties:
              type: string
          description: Any extra metadata that needs to be shared by the caller as key/value pair
          example:
            key1: "value1"
            key2: "value2"
          nullable: true
    linkResponse:
      type: object
      properties:
        requestId:
          type: string
          description: Unique Iddentifier for your request.
          example: 6584cc10-8959-4fed-9cdc-6c981a93d58c
        mobileNumber:
          type: string
          description: "Mobile number of the customer"
          example: "+91 9812345670"
        expiryDate:
          type: string
          format: date-time
          example: "2025-06-30T12:00:00Z"
    documentSearchResponse:
      type: object
      properties:
        mobileNumber:
          type: string
          description: "Mobile number of the customer"
          example: "+91 9812345670"
        dealerCode:
          type: string
          description: "Dealer Code"
          example: "dealer123"
        uploadedDate:
          type: string
          format: date-time
        uploadStatus:
          type: string
          example: "document-uploaded"
        documents:
          type: array
          items:
            $ref: '#/components/schemas/documentDetails'
    documentDetails:
      type: object
      properties:
        documentType:
          type: string
          description: "Type of the document"
          example: "ID_PROOF"
        fileName:
          type: string
          description: "Original file name of the document"
          example: "adhar_card.pdf"
        fileSize:
          type: integer
          description: "Size of the file in bytes"
          example: 1024567
        downloadLink:
          type: string
          description: "Link to download the document"
          example: "https://dms.bajajauto.com/api/document/download/1234567890"
    errorResponse:
      type: object
      properties:
        error:
          type: string
          example: Bad request
        errorDetails:
          type: array
          items:
            type: string
    