name: Azure Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: webapp-bajajoneanddone
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "20.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          resource-group-name: "rg-bajaj-oneanddone"
          startup-command: "npx next start -p $PORT"

      - name: Azure logout
        run: az logout
